---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: minimal

dist: xenial

# Use the new container infrastructure
sudo: false

# Install packages
install: true

# Run
script:

  - |
    set -x; ssh -V;
    : "install.sh" && {
      bash -n install.sh &&
      bash -x install.sh && {
        [ -r "$HOME/.ssh/config" ] &&
        [ -r "$HOME/.ssh/default.conf" ] &&
        [ -d "$HOME/.ssh/config.d/" ] &&
        [ -d "$HOME/.ssh/keys/" ] &&
        [ -x "$HOME/.ssh/ssh_config_cat.sh" ] &&
        [ -x "$HOME/.ssh/ssh_config_check.sh" ] &&
        ( cd "${HOME}/.config/dot-ssh-files" &&
          git config --get core.filemode |
          egrep -i '^false$'; )
      }
    } &&
    : "ssh_config_check.sh" && {
      bash -n "$HOME/.ssh/ssh_config_cat.sh" &&
      bash -x "$HOME/.ssh/ssh_config_cat.sh" |
      egrep -i '^[[:space:]]*(LogLevel[[:space:]]+VERBOSE|CheckHostIP[[:space:]]+no)[[:space:]]*$'
    } &&
    : "OK";

# Notifications
#notifications:
#  email:
#  - your@emailaddress

