---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: minimal

dist: xenial

# Use the new container infrastructure
sudo: false

# Install packages
install: true

# Run
script:

  - |
    set -x;
    ssh -V;
    ssh -oInclude=/dev/null localhost 2>&1 |
    egrep -i 'Bad[ \t]+configuration[ \t]+option:[ \t]+include' &&
    echo OK || echo NG
    bash -n install.sh &&
    bash -x install.sh && {
      [ -r "$HOME/.ssh/config" ] &&
      [ -r "$HOME/.ssh/default.conf" ] &&
      [ -d "$HOME/.ssh/config.d/" ] &&
      [ -d "$HOME/.ssh/keys/" ] &&
      [ -x "$HOME/.ssh/ssh_config_cat.sh" ] && {
        cat "${HOME}/.config/dot-ssh-files/.git/config" |
        egrep -i 'filemode[ \t]+=[ \t]+false'
      }
    } &&
    ssh -Gv localhost |
    egrep -i '^[ \t]*(LogLevel[ \t]VERBOSE|CheckHostIP[ \t]+no)[ \t]*$' &&
    : "OK";

# Notifications
#notifications:
#  email:
#  - your@emailaddress

