---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: minimal

dist: xenial

# Use the new container infrastructure
sudo: false

# Install packages
install: true

# Run
script:

   - bash -Cu .tests.sh

# Notifications
#notifications:
#  email:
#  - your@emailaddress

